export const browserCoreExamples = [
  "claw browser status",
  "claw browser start",
  "claw browser stop",
  "claw browser tabs",
  "claw browser open https://example.com",
  "claw browser focus abcd1234",
  "claw browser close abcd1234",
  "claw browser screenshot",
  "claw browser screenshot --full-page",
  "claw browser screenshot --ref 12",
  "claw browser snapshot",
  "claw browser snapshot --format aria --limit 200",
  "claw browser snapshot --efficient",
  "claw browser snapshot --labels",
];

export const browserActionExamples = [
  "claw browser navigate https://example.com",
  "claw browser resize 1280 720",
  "claw browser click 12 --double",
  'claw browser type 23 "hello" --submit',
  "claw browser press Enter",
  "claw browser hover 44",
  "claw browser drag 10 11",
  "claw browser select 9 OptionA OptionB",
  "claw browser upload /tmp/file.pdf",
  'claw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "claw browser dialog --accept",
  'claw browser wait --text "Done"',
  "claw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "claw browser console --level error",
  "claw browser pdf",
];
