export const browserCoreExamples = [
  "newclaw browser status",
  "newclaw browser start",
  "newclaw browser stop",
  "newclaw browser tabs",
  "newclaw browser open https://example.com",
  "newclaw browser focus abcd1234",
  "newclaw browser close abcd1234",
  "newclaw browser screenshot",
  "newclaw browser screenshot --full-page",
  "newclaw browser screenshot --ref 12",
  "newclaw browser snapshot",
  "newclaw browser snapshot --format aria --limit 200",
  "newclaw browser snapshot --efficient",
  "newclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "newclaw browser navigate https://example.com",
  "newclaw browser resize 1280 720",
  "newclaw browser click 12 --double",
  'newclaw browser type 23 "hello" --submit',
  "newclaw browser press Enter",
  "newclaw browser hover 44",
  "newclaw browser drag 10 11",
  "newclaw browser select 9 OptionA OptionB",
  "newclaw browser upload /tmp/file.pdf",
  'newclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "newclaw browser dialog --accept",
  'newclaw browser wait --text "Done"',
  "newclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "newclaw browser console --level error",
  "newclaw browser pdf",
];
