export const browserCoreExamples = [
  "iflow browser status",
  "iflow browser start",
  "iflow browser stop",
  "iflow browser tabs",
  "iflow browser open https://example.com",
  "iflow browser focus abcd1234",
  "iflow browser close abcd1234",
  "iflow browser screenshot",
  "iflow browser screenshot --full-page",
  "iflow browser screenshot --ref 12",
  "iflow browser snapshot",
  "iflow browser snapshot --format aria --limit 200",
  "iflow browser snapshot --efficient",
  "iflow browser snapshot --labels",
];

export const browserActionExamples = [
  "iflow browser navigate https://example.com",
  "iflow browser resize 1280 720",
  "iflow browser click 12 --double",
  'iflow browser type 23 "hello" --submit',
  "iflow browser press Enter",
  "iflow browser hover 44",
  "iflow browser drag 10 11",
  "iflow browser select 9 OptionA OptionB",
  "iflow browser upload /tmp/file.pdf",
  'iflow browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "iflow browser dialog --accept",
  'iflow browser wait --text "Done"',
  "iflow browser evaluate --fn '(el) => el.textContent' --ref 7",
  "iflow browser console --level error",
  "iflow browser pdf",
];
